version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UTNExamen
      MYSQL_USER: utn
      MYSQL_PASSWORD: utnpass
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
